config/routes.rb
RottenMangoes::Application.routes.draw do

  namespace :admin do
    resources :users
  end

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users
  resource :session
  root to: 'movies#index'

end

  

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews

  mount_uploader :image, ImageUploader

  # validates :title, 
  #   presence: true
  # validates :director, 
  #   presence: true
  # validates :runtime_in_minutes, 
  #   numericality: { only_integer: true }
  # validates :description, 
  #   presence: true
  # validates :release_date, 
  #   presence: true

  # validate :release_date_is_in_the_past

  def review_average
    if reviews.size == 0
      "There have been no reviews for this movie."
      
    else
      average = reviews.sum(:rating_out_of_ten)/reviews.size
      "Review Average: #{average} / 10"
    end
  end

  def self.movies_by_runtime(runtime)
    case runtime.to_i
      when 1
        Movie.where("runtime_in_minutes < 90")
      when 2
        Movie.where("runtime_in_minutes >= 90 AND runtime_in_minutes <= 120")
      when 3
        Movie.where("runtime_in_minutes > 120")
      end
  end



  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }
    
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews

  has_secure_password

  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: { in: 2..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end
  
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController

    before_action :not_authorized?

  # GET /admin/users
  # GET /admin/users.json
    def index
      @users = User.all.page(params[:page]).per(10)
    end

  # GET /admin/users/1
  # GET /admin/users/1.json

    # GET /admin/users/new
    def new
      @user = User.new
    end

    # GET /admin/users/1/edit
    def edit
      @user = User.find(params[:id])
    end

    # POST /admin/users
    # POST /admin/users.json
    def create
      @user = User.new(user_params)

      if @user.save
        session[:user_id] = @user.id
        redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
      else
        render :new
      end
    end

    # PATCH/PUT /admin/users/1
    # PATCH/PUT /admin/users/1.json
    def update
      @user = User.find(params[:id])

      if @user.update_attributes(user_params)
        redirect_to admin_users_path(@user)
      else 
        render :edit
      end
    end

    # DELETE /admin/users/1
    # DELETE /admin/users/1.json
    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to admin_users_path
    end

    private

    def not_authorized?
      unless current_user && current_user.admin
        redirect_to movies_path, notice: "Oops! You're not allowed to access this page."  
      end
    end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    if params[:query].present? && params[:runtime_in_minutes].present?
      @movies_with_runtime = Movie.movies_by_runtime(params[:runtime_in_minutes])
      @movies = @movies_with_runtime.where("title LIKE ? OR director LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
    elsif params[:query].present?
      @movies = Movie.where("title LIKE ? OR director LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
    elsif params[:runtime_in_minutes].present?
      @movies = Movie.movies_by_runtime(params[:runtime_in_minutes])
    else 
      @movies = Movie.all
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end   

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save 
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else 
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :image
      )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end 
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else 
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_users_path(@user)
    else 
      render :edit
    end
  end  

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    UserMailer.account_destroyed_email(@user)
    redirect_to admin_users_path
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<table>
<th><h1><strong>All Users</strong></h1></th1>

<div class="paginate"><%= paginate @users %></div>
<% @users.each do |user| %>
  <tr>
    <td>Email: <%= user.email %>   </td>
    <td>Full Name: <%= user.full_name %>   </td>
    <td>Admin: <%= user.admin %>   </td>
    <td>Created At: <%= user.created_at %>   </td>
    <td>Last Update: <%= user.updated_at %>   </td>
    <td><%= link_to "edit", edit_admin_user_path(user) %></td>
    <td> <%= link_to "delete", user_path(user), method: :delete, data: { confirm: "You sure?" } %></td>
  </tr>
<% end %>
</table>
<p class="new-user"><%= link_to "Create a New User", new_admin_user_path %></p>

app/views/admin/users/new.html.erb
<h1>New User</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div>
    <%= f.label "admin" %>
    <%= f.radio_button :admin, true, :checked => true %>
    <%= f.label "not admin" %>
    <%= f.radio_button :admin, false %>
  </div>
  <br>
  <a class="waves-effect waves-light btn"><%= submit_tag "Submit" %></a>
  <br>
<% end %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
<br>
    <% if current_user %>
        <% if current_user.admin %>
          Welcome Admin User: <%= current_user.full_name %> | 
           <%= link_to "Admin Page", admin_users_path %>  |  <%= link_to "Regular View", movies_path %>  | 
        <% else %>
          Signed in as <%= current_user.full_name %>|
        <% end %>
      <%= link_to "Log out", session_path("current"), method: :delete %>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %> 
    <% end %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
  <div class="nav">
    <h1 class="brand-logo left"> ✩ Rotten Mangos ✩ </h1>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <h5> ✇ Find, Review and Discover the Best Films!</h5>
        <li><%= link_to "View all Movies!", movies_path %></li>
        <li><%= link_to "Submit a movie!", new_movie_path %></li>
      </ul>
  </div>
</nav>
  <br>
  <br>
<div class="container">
  <br>
  <br>
  <br>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
</div>
  <br>
  <br>
  <br>
  <br>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "release_date" %><br>
    <%= f.date_field "release_date" %>
  </div>
  <div>
    <%= f.label "director" %><br>
    <%= f.text_field "director" %>
  </div>
  <div>
    <%= f.label "runtime_in_minutes" %><br>
    <%= f.text_field "runtime_in_minutes" %>
  </div>
  <div>
    <%= f.label "description" %><br>
    <%= f.text_area "description" %>
  </div>
  <div>
    <%= f.label "URL" %><br>
    <%= f.text_field "poster_image_url" %>
  </div>
  <div>
    <%= f.label "image" %><br>
    <%= f.file_field "image" %>
  </div>
  <br>
  <a class="waves-effect waves-light btn"><%= submit_tag "Submit" %></a>
  <br>
<% end %>

app/views/movies/_movie.html.erb
<div class="movies">
<br>
<% @movies.each do |movie| %>
    <div>
      <%= image_tag movie.image_url(:thumb).to_s %>
    </div>
    <h5><%= link_to movie.title, movie_path(movie) %> | <%= movie.review_average %></h5>
    <p><%= formatted_date(movie.release_date) %></p>
    <p>Director: <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</p>
    <p><%= movie.description %></p>
    <% if movie.poster_image_url.present? %>
    <p>Check it out at: <%= link_to movie.poster_image_url, movie.poster_image_url %></p>
    <% end %>
    <hr>
<% end %>
</div>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<div class="row">
<form class="col s12">
<br>
<p class="search">Search for a Movie!</p>
<br>
<div class="input-field col s4"><%= form_tag movies_path, method: :get do %>
  <%= text_field_tag :query, nil, placeholder: "By Title or Director:" %></div>
  <div class="input-field col s4">
    <%= select_tag(:runtime_in_minutes, options_for_select([["Under 90 Minutes", 1], ["Between 90 and 120 Minutes", 2], ["Over 120 Minutes", 3]]), :prompt => "By Length") %></div>
  <br>
  <a class="waves-effect waves-light btn"><%= submit_tag("Search") %></a>
<% end %>
</form>
</div>

<%= render "movie" %>

app/views/movies/new.html.erb
<h4>Submit a movie!</h4>
<%= render 'form' %>

app/views/movies/show.html.erb
<div class="movies">
  <%= image_tag @movie.image_url(:thumb).to_s %>
<h5><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, data: { confirm: "You sure?" } %>) | <%= @movie.review_average %></h5>
<p><%= formatted_date(@movie.release_date) %></p>
<p>Director: <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</p>
<p><%= @movie.description %></p>
</div>

<hr>

<h6>Reviews of <em><%= @movie.title %></em></h6>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= review.user.full_name %></small><br/>
  <% end %>
  <br>
  <br>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "text" %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label "rating_out_of_ten" %><br>
    <%= f.number_field "rating_out_of_ten" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/new.html.erb
<br>
<br>
<br>
<h4>Sign Up</h4>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
    <a class="waves-effect waves-light btn"><%= submit_tag "Log In" %></a>
<% end %>
<br>
<br>